### ISSUE TITLE
[FE] 중간 리팩터링

### ISSUE THREAD

**Issue by euijinkk** [woowacourse-teams/2022-kkogkkog#105]
## 배경

리팩터링!

## 진행사항
  - [ ] 모달 띄우는 로직
  - [ ] 모달 컴포넌트
  - [ ] 애니메이션 띄우는 로직
  - [ ] useQuery 훅
  - [ ] axios - transformResponse 걷어내기
  - [ ] useMutation
  - [ ] KkogKkogList , Sent/ReceivedKkogKkog 추상화
  - [ ] KkogKkogItem / Preview
  - [ ] TS - any 부채 해결

**Comment by juunzzi** [comment]
## 배경

리팩터링!

## 진행사항
  - [x] 모달 띄우는 로직
  - [x] 모달 컴포넌트
  - [ ] 애니메이션 띄우는 로직
  - [ ] useQuery 훅
  - [ ] axios - transformResponse 걷어내기
  - [ ] useMutation
  - [x] KkogKkogList , Sent/ReceivedKkogKkog 추상화
  - [x] KkogKkogItem / Preview
  - [ ] TS - any 부채 해결

**Comment by juunzzi** [comment]
## 배경

리팩터링!

## 진행사항
  - [ ] 애니메이션 띄우는 로직
  - [ ] useQuery 훅
  - [ ] axios - transformResponse 걷어내기
  - [ ] useMutation
  - [ ] TS - any 부채 해결
  - [ ] UserSearchForm, UserSearchModal 컴포넌트 리팩터링 (Suspense 적용)

**Comment by juunzzi** [comment]
UI 개선작업이 우선순위가 높아 나머지 작업들은 이후에 처리합니다

**Comment by juunzzi** [comment]
## 배경
시지프의 React-Query 리팩터링 이후 작업

## 진행사항
  - [ ] 애니메이션 띄우는 로직
  - [ ] UserSearchForm, UserSearchModal 컴포넌트 리팩터링 (Suspense 적용)
  - [ ] useQuery 기반의 훅, useMutation 기반의 훅 논의된 사용법에 맞게 수정. 
  - [ ] useMutation의 mutate 객체를 활용하는 비즈니스 로직들을 훅으로 응집하는 작업
  - [ ] 네이밍 규칙에 맞게 useQuery, useMutation 훅 네이밍 수정

**Comment by juunzzi** [comment]
## 배경
시지프의 React-Query 리팩터링 이후 작업

## 진행사항
  - [ ] 애니메이션 띄우는 로직
  - [ ] UserSearchForm, UserSearchModal 컴포넌트 리팩터링 (Suspense 적용)
  - [x] useQuery 기반의 훅, useMutation 기반의 훅 논의된 사용법에 맞게 수정. 
  - [x] useMutation의 mutate 객체를 활용하는 비즈니스 로직들을 훅으로 응집하는 작업
  - [x] 네이밍 규칙에 맞게 useQuery, useMutation 훅 네이밍 수정

**Comment by juunzzi** [comment]
## 배경
이제 두 개 남았지롱!

## 진행사항
  - [ ] 애니메이션 띄우는 로직
  - [ ] UserSearchForm, UserSearchModal 컴포넌트 리팩터링 (Suspense 적용)
