### ISSUE TITLE
[BE] 디폴트 닉네임 형식을 귀엽게 만들기

### ISSUE THREAD

**Issue by bugoverdose** [woowacourse-teams/2022-kkogkkog#281]
## 배경

- 현재 회원가입 사용자 플로우에서 사용자는 '익명1234'와 같은 형식의 닉네임을 디폴트로 부여받고 닉네임을 수정하도록 한다.
- 문제는 사용자가 이 '익명1234' 형식의 디폴트 닉네임이 자신에게 부여되는 것을 직접 확인할 수 있다는 점. 
- 이왕 사용자가 이것을 볼 수 있으므로 차라리 좀 귀엽게 만들어보자 

## 진행사항

- [x] `형용사 + 동물명` 형식으로 닉네임 임의로 생성하여 회원 생성 (ex. 귀여운코끼리, 나쁜보아뱀 등)

**Comment by Hyunta** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ귀여운 이름 적극 찬성이요

**Comment by DWL21** [comment]
ㅋㅋ
