### ISSUE TITLE
[FE] fetcher 함수의 response에서 data만 추출하여 return 한다.

### ISSUE THREAD

**Issue by euijinkk** [woowacourse-teams/2022-kkogkkog#342]
## 배경

- status code와 message를 AxiosError 에서 얻을 수 있으므로, response 그 자체를 사용하지 않을 것입니다. 
- data?.data?.data 체이닝 코드를 줄이기 위해서!

**Comment by juunzzi** [comment]
굳 fetcher 함수를 고도화하는게 나을거 같아요 ~~ 이제는 니즈가 생긴 것 같습니다 ! 제 [리팩토링 결과](https://github.com/woowacourse-teams/2022-kkogkkog/pull/340) useMemo와 같은 코드가 불필요하게 작성되어야 해서 좋지 않은 것 같아요 ㅎㅎ. 그렇다고 AxiosResponse에서 따로 필요한 데이터가 있는 것도 아니구요 ! 얼른 진행해봅시다 !!
