### ISSUE TITLE
[All] 비회원에게 쿠폰을 보내기

### ISSUE THREAD

**Issue by euijinkk** [woowacourse-teams/2022-kkogkkog#347]
# 1차 아이디어 - 쿠폰 코드 (with 정, 시지프)
url 을 만든다. ?couponCode={string} - query string 형식으로 보낸다. 이 형식으로 url을 지인에게 전송하고, 지인이 url로 들어가면 로그인을 유도하고 로그인이 완료된 후 <쿠폰 발급 받기> 페이지로 보낸다. query string에서 받아온 couponCode를 로컬스토리지에 저장해두고, 이 값을 그대로 Input에 넣어준다.

**Comment by juunzzi** [comment]
굳 너무좋다 진짱
