### ISSUE TITLE
[FE] 웹 접근성을 고려한다.

### ISSUE THREAD

**Issue by euijinkk** [woowacourse-teams/2022-kkogkkog#444]
## 배경

웹 접근성을 고려한다.

**Comment by kwannee** [comment]
### 공통
뒤로가기 버튼이 선택이 안돼서 나갈 수가 없다.
어떤 페이지인지에 대한 멘트가 없어서 어떤 페이지를 보고 있는지 알 수가 없다.

### 홈
받는 사람 검색 모달을 닫을 수 없다.

### 보낸 쿠폰
보낸 쿠폰을 사용했는데 코멘트가 없어서 제대로 사용된 건지 알 수 없다.
해시태그를 # 고마워요라고 읽는데 메세지의 일부인지 해시태그인지 알 수 없다.

### 쿠폰 보내기
쿠폰을 완성해보세요! 라는 멘트가 뭔가 동작을 유도하는 것 같아서 누르게 되는데 별 기능이 없다.
받을 유저를 찾는 모달이 떴을 때 자동으로 포커스가 안가서 검색하기가 쉽지 않다. 혹은 다음 요소로 넘기더라도 유저 검색모달로 가지 않는다.
받을 유저 목록에서 이메일 감싸는 괄호를 다 읽어서 헷갈릴 수 있음. ex. '여는 괄호, abc@abc.com, ‘닫는 괄호’
받을 유저 모달을 끌 수가 없다.
모달 안닫혀서 보내기에 실패했음.
쿠폰을 보내고 toast를 읽어 주지 않아서 성공했는지 실패했는지 알 수 없음.

**Comment by euijinkk** [comment]
- 프사를 이상하게 읽는다. "프사 방문함 링크 이미지 앤드 헤더"
- 모달에 role이 없어서 모달 내 셀렉트가 안 된다. 시각 장애인은 끄는 것도 불가능하다.
- 돋보기 이미지 alt 를 "돋보기"라고 읽는다.
- hashtag에서 "숫자기호" 안읽게 만들기
- 쿠폰 종류 마다 정상적인 alt를 주어야한다. (커피, 식사, 술 구분하기)
- 보내는 사람 삭제가 불가능하다. 이름을 읽으며 취소할 건지 물어봐야한다.
- toast 를 읽어줘야 한다.
- 뒤로 가기가 불가능하다.
- ( 목 ) 따로따로 읽는다.
- 히스토리 bell 은 읽지 않는다.
- 0 / 200 은 이해할 수 없을 것이다.
