### ISSUE TITLE
[BE] 벡엔드 코드 스타일을 공통화

### ISSUE THREAD

**Issue by Wishoon** [woowacourse-teams/2022-kkogkkog#78]
## 배경

현재 각 작업자들의 Java Code Style이 달라 리뷰 시 필요 없는 부분까지 새롭게 갱신되는 문제가 있음

## 진행사항

- Java Code Style을 통합한다.

  - [x] Google Java Style을 기준으로 KkogKkog Java Style을 생성한다.
  - [x] 모든 백엔드 코드에 대해 해당 스타일을 적용한다.

**Comment by bugoverdose** [comment]
?
